@startuml

state Play {

    state DisplayBall {
        [*] --> MoveBall
        MoveBall : Move the ball\naccording the tilt\nof the board
        MoveBall --> MoveBall : ball Inside\nThe Board\nAnd Did Not\nHit the Wall
        MoveBall --> WinAnimation : Ball\nHited\nThe wall
        MoveBall --> EraseBall :  Ball Moved\nOutside The Board

        WinAnimation : Added points to the game score
        WinAnimation --> WinAnimation : winningAnimation
        WinAnimation --> DisplayWall : winnedPoints
        WinAnimation --> MoveBall : WallCreated

        EraseBall : Ball erasing
        EraseBall --> [*]
    }

    state DisplayWall {
        [*] --> CreateWall
        CreateWall : Create a wall on a random side
        CreateWall --> FixWall : wallCreated

        FixWall --> FixWall : timeout\nBefore\nWall Blinking\nIs Not Over
        FixWall --> BlinkWall : timeout\nBefore\nWall Blinking\nIs Over
        
        BlinkWall --> BlinkWall : wallBlinking
        BlinkWall --> EraseWall : timeout\nWall Blinking\nIs Over

        EraseWall --> EraseWall : wallErasing
        EraseWall --> [*]
    }
}

Play --> GameOver : gameOver
GameOver : Display score

@enduml
